### ISSUE TITLE
Czechia - Response signature verification

### ISSUE THREAD

**Issue by KaliCZ** [MewsSystems/fiscalizations#107]
If a response is a valid success, it should be signed by the certificate of EET. Verify the signature. As the process is performance consuming and not really reliable, let's make it an optional feature.

via @todvora (thx):
>  K ověření revokace existují dva způsoby - CRL (certificate revocation lists) nebo OCSP (Online Certificate Status Protocol). I.CA poskytuje v tomto případě obě dvě možnosti.

**Comment by abdallahbeshi** [comment]
EET is no longer supported - the project was shutdown by the tax authorities.
