### ISSUE TITLE
Hungary fiscalization - Method not found (NavClient)

### ISSUE THREAD

**Issue by Cvijo** [MewsSystems/fiscalizations#156]
Hungary Fiscallization
Installing via Nuget package (Hungary)

When creating NavClient 

```
var navClient = new NavClient(
                new TechnicalUser(
                    Login.Create("xxxx").Success.Get(),
                    "xxxx",
                    SigningKey.Create("xxxx").Success.Get(),
                    LocalTaxpayerIdentificationNumber.Create("xxxx").Success.Get(),
                    EncryptionKey.Create("xxxx").Success.Get()),
                new SoftwareIdentification(SOFTWARE_ID, SOFTWARE_NAME, SoftwareType.OnlineService, SOFTWARE_VERSION, "xxxx", "xxxx", "XX"),
                NavEnvironment.Test
                );
```

line LocalTaxpayerIdentificationNumber.Create("xxx").Success.Get() throw exception

`Method not found: 'FuncSharp.ITry`2<Mews.Fiscalizations.Core.Model.TaxpayerIdentificationNumber,Mews.Fiscalizations.Core.Model.Error> Mews.Fiscalizations.Core.Model.TaxpayerIdentificationNumber.Create(Mews.Fiscalizations.Core.Model.Country, System.String, Boolean)'`

But if I download your code, it works, but via Nuget it throws an error.

**Comment by abdallahbeshi** [comment]
Hi @Cvijo, thanks for reaching out.

Seems like there is an issue with the project references, we will work on a fix and release a new version.
As a workaround, for now, you can reference [Mews.Fiscalizations.All](https://www.nuget.org/packages/Mews.Fiscalizations.All)
and it should work fine.

Thank you again for reporting the issue.
Have a nice day!

Abdal

**Comment by abdallahbeshi** [comment]
Dear @Cvijo, We fixed the issue, please update to the latest version of [Mews.Fiscalizations.Hungary](https://www.nuget.org/packages/Mews.Fiscalizations.Hungary/10.0.0).

Thanks :)
