### ISSUE TITLE
Q&A - Hungary - hard coded values, tax-exampt

### ISSUE THREAD

**Issue by Cvijo** [MewsSystems/fiscalizations#159]
Hi @abdallahbeshi, 

This is a question, not a bug report

I see in Hungary's fiscalization that some values when mapping to Dto is hardcoded

```
                        invoiceAppearance = Dto.InvoiceAppearanceType.ELECTRONIC,
                        invoiceCategory = Dto.InvoiceCategoryType.AGGREGATE,
```
Is there a specific reason why the category is always Aggregate, not Normal?

What about tax-exempt (vatExemption/case AAM, TAM, KBAET, ...) and reverse charge options, is this something you might add in the future?

**Comment by abdallahbeshi** [comment]
Hi @Cvijo, we built the library to mostly fit our needs, and that's the reason you might find some hard-coded stuff like the example you mentioned.

In case you'd like to cover the other cases, please feel free to extend the library and create a PR.
